[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'vim-denops/denops.vim'

#[[plugins]]
#repo = 'higashi000/dps-kakkonan'
#hook_source = '''
#vmap ( <Plug>(dps_kakkonan_surround_parenthesis)
#vmap { <Plug>(dps_kakkonan_surround_curly)
#vmap [ <Plug>(dps_kakkonan_surround_square)
#vmap " <Plug>(dps_kakkonan_surround_doublequote)
#vmap ' <Plug>(dps_kakkonan_surround_singlequote)
#vmap ` <Plug>(dps_kakkonan_surround_backquote)
#
#let g:kakkonan_custom_brackets = {
#      \ "h1": {
#      \ "start": "<h1>",
#      \ "finish": "</h1>"
#      \ },
#      \ "script": {
#      \ "start": "<script>",
#      \ "finish": "</script>"
#      \ },
#      \ "<": {
#      \ "start": "<",
#      \ "finish": ">"
#      \ },
#      \ }
#
#map rp( <Plug>(dps_kakkonan_replace_parenthesis)
#map rp{ <Plug>(dps_kakkonan_replace_curly)
#map rp[ <Plug>(dps_kakkonan_replace_square)
#map rp" <Plug>(dps_kakkonan_replace_doublequote)
#map rp' <Plug>(dps_kakkonan_replace_singlequote)
#map rp` <Plug>(dps_kakkonan_replace_backquote)
#map <Leader>dk <Plug>(dps_kakkonan_delete_brackets)
#'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
colorscheme iceberg
set background=dark
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
hooks_file = '$HOME/dotfiles/hooks/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hooks_file = '$HOME/dotfiles/hooks/defx.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescriptreact']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['typescript', 'typescriptreact']
build = 'npm install'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_func = 's:defx_my_settings'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'iceberg'
'''

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'higashi000/sarahck.vim'
